version: '3.8'

services:
  facebook-video-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - RATE_LIMIT_REQUESTS=10
      - RATE_LIMIT_WINDOW=60
      - MAX_VIDEO_SIZE_MB=500
      - DOWNLOAD_TIMEOUT=30
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s