# Netlify deployment configuration
[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "static"

[functions]
  python_version = "3.11"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
